### PR TITLE
[v5.3] Artifact name fixes as discussed in #26.

### PR DESCRIPTION
**Pull request by lsm5**
PR #26 contained some changes for fixing artifact names and getting rid of source files in the final artifact list. This PR incorporates those changes into the main branch.

Additionally, reduce the envvars in podman-rpm-info-vars.sh and get them from the container itself.

(cherry picked from commit 70490e2dc3f8d37be4e547cb0e0109cb0c33bec9)

Switch `PODMAN_RPM_TYPE` in podman-rpm-info-vars.sh to `release` to build release rpms.

```release-note
None
```

### CODE REVIEW

**Comment by lsm5** [comment]
@baude release artifacts are generated for 5.3 rc2. 

x86_64 https://artifacts.dev.testing-farm.io/d7733160-a444-4979-9352-8792d65ebe05/work-build_and_verifyk9zmkpg3/plans/build_and_verify/execute/data/guest/default-0/script-00-1/data/

aarch64 https://artifacts.dev.testing-farm.io/02df3994-50d7-481b-bbde-55910b8af4a3/work-build_and_verifyka98red0/plans/build_and_verify/execute/data/guest/default-0/script-00-1/data/

**Comment by lsm5** [comment]
@baude if the artifacts look ok, I'd like to have this merged before we release v5.3.0 so at least the artifact building can be done without too much effort on release

**Comment by baude** [comment]
i was not merging due to test failures. are we going to fix those ?

**Comment by lsm5** [comment]
@baude I've updated this to use 5.3.0-rc3. So at least the artifacts should be built here, unless it barfs for other reasons. I'll check back in maybe a couple of hours.

**Comment by lsm5** [comment]
https://status.testing-farm.io/issues/2024-11-07-testing-farm-deployment/ <- quite some wait queue for testing-farm jobs so I guess these might take a while. There was also a new testing farm release today so don't know if that causes any other issues. I'll not trigger any new jobs here to avoid further increasing the queue.

**Pull request closed without merging**
