### PR TITLE
make scripts executable

### PR DESCRIPTION
**Pull request by Luap99**
```release-note
None
```

### CODE REVIEW

**Review by lsm5 — APPROVED** [review]
LGTM

**Comment by baude** [comment]
failure due to jq not being on the image in question?

**Comment by baude** [comment]
fwiw, I am cool with the PR.

**Comment by Luap99** [comment]
I don't know about the tmt problems, I guess the issue might be that it switched to f41? Anyhow it should not be related to this change and I would say this should be pretty safe to merge regardless

**Comment by lsm5** [comment]
jq and dosfstools not being present on f41 for whatever reason. It's handled in a PR of mine.

**Pull request merged**
