### PR TITLE
Push image automatically

### PR DESCRIPTION
**Pull request by Luap99**
```release-note
quay.io images will now be pushed automatically by cirrus post merge
```

### CODE REVIEW

**Comment by Luap99** [comment]
Ok build times are back to old values thanks to the no compression bits. Now the aarch build took ~13 mins from the ~30 mins before so this is very good.

**Comment by Luap99** [comment]
@lsm5 @baude This should now push the proper image post merge (but well hard to test, I did tested the pushes here against stage-podman-machine which worked fine)
This also contains the change for the new script coreos uncompressed changes

**Comment by baude** [comment]
LGTM

**Pull request merged**
