### PR TITLE
Enable tests for Windows HyperV

### PR DESCRIPTION
**Pull request by baude**
You can now test Windows HyperV machine images using the verify test suite.  This PR includes some windows specific things.  It also includes a powershell script that mimics the run_test.sh used for Linux and MacOS.  And finally, updated the documentation to reflect how Windows HyperV can be tested.

### CODE REVIEW

**Comment by baude** [comment]
@lsm5 PTAL

**Comment by rhatdan** [comment]
LGTM

**Comment by lsm5** [comment]
@baude I can test this after creating v5.2.2 PR today. Could you please give me the exact steps to run this on Windows. I got a windows vm to try this out on.

**Comment by baude** [comment]
I would grab the 5.2.2 installer, install it; then the 5.2.2 disks when I make them.  Otherwise, the README should get you there.

**Comment by lsm5** [comment]
> I would grab the 5.2.2 installer, install it; then the 5.2.2 disks when I make them. Otherwise, the README should get you there.

The script in README asks for path to disk, so I guess I gotta wait for the disk anyway? I can merge this right away if it makes life easier.

**Review by lsm5 — APPROVED** [review]
LGTM with a cursory look. I'm unable to test this on my VM right now as enabling hyperv and rebooting is causing my VM to crash (don't know if hyperv is itself to blame though).

Hopefully we can test this reliably in CI soon.

**Pull request merged**
